linters:
  enable-all: true
  disable:
    # deprecated
    - golint
    - interfacer
    - maligned
    - scopelint

    # less useful
    - cyclop
    - exhaustivestruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gomnd
    - ireturn
    - nolintlint
    - varnamelen

linters-settings:
  misspell:
    ignore-words:
      - strat
  nlreturn:
    block-size: 2
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
      - paralleltest
      text: "does not use range value in test Run"
